INSERT INTO "COMPANY" (ID, VERSION, NAME) VALUES
(6, 1, 'Phillips Van Heusen Corp.'),
(7, 1, 'Avaya Inc.'),
(8, 1, 'Laboratory Corporation of America Holdings'),
(9, 1, 'AutoZone, Inc.'),
(10, 1, 'Linens ''n Things Inc.');   
INSERT INTO "CONTACT" (ID, VERSION, EMAIL,FIRST_NAME,LAST_NAME,COMPANY_ID) VALUES
(11, 1, 'eula.lane@jigrormo.ye', 'Eula', 'Lane', 8),
(12, 1, 'barry.rodriquez@zun.mm', 'Barry', 'Rodriquez', 7),
(13, 1, 'eugenia.selvi@capfad.vn', 'Eugenia', 'Selvi', 6),
(14, 1, 'alejandro.miles@dec.bn', 'Alejandro', 'Miles', 10),
(15, 1, 'cora.tesi@bivo.yt', 'Cora', 'Tesi', 6),
(16, 1, 'marguerite.ishii@judbilo.gn', 'Marguerite', 'Ishii', 10),
(17, 1, 'mildred.jacobs@joraf.wf', 'Mildred', 'Jacobs', 8),
(18, 1, 'gene.goodman@kem.tl', 'Gene', 'Goodman', 8),
(19, 1, 'lettie.bennett@odeter.bb', 'Lettie', 'Bennett', 6),
(20, 1, 'mabel.leach@lisohuje.vi', 'Mabel', 'Leach', 10),
(21, 1, 'jordan.miccinesi@duod.gy', 'Jordan', 'Miccinesi', 8),
(22, 1, 'marie.parkes@nowufpus.ph', 'Marie', 'Parkes', 7),
(23, 1, 'rose.gray@kagu.hr', 'Rose', 'Gray', 9),
(24, 1, 'garrett.stokes@fef.bg', 'Garrett', 'Stokes', 9),
(25, 1, 'barbara.matthieu@derwogi.jm', 'Barbara', 'Matthieu', 7),
(26, 1, 'jean.rhodes@wehovuce.gu', 'Jean', 'Rhodes', 7),
(27, 1, 'jack.romoli@zamum.bw', 'Jack', 'Romoli', 6),
(28, 1, 'pearl.holden@dunebuh.cr', 'Pearl', 'Holden', 8),
(29, 1, 'belle.montero@repiwid.si', 'Belle', 'Montero', 9),
(30, 1, 'olive.molina@razuppa.ga', 'Olive', 'Molina', 6),
(31, 1, 'minerva.todd@kulmenim.ad', 'Minerva', 'Todd', 9),
(32, 1, 'bobby.pearson@ib.kg', 'Bobby', 'Pearson', 9),
(33, 1, 'larry.ciappi@ba.lk', 'Larry', 'Ciappi', 10),
(34, 1, 'ronnie.salucci@tohhij.lv', 'Ronnie', 'Salucci', 9),
(35, 1, 'walter.grossi@tuvo.sa', 'Walter', 'Grossi', 9);
INSERT INTO "CONTACT" (ID, VERSION, EMAIL,FIRST_NAME,LAST_NAME,COMPANY_ID) VALUES
(36, 1, 'frances.koopmans@foga.tw', 'Frances', 'Koopmans', 7),
(37, 1, 'frances.fujimoto@uswuzzub.jp', 'Frances', 'Fujimoto', 6),
(38, 1, 'olivia.vidal@hivwerip.vc', 'Olivia', 'Vidal', 9),
(39, 1, 'edna.henry@gugusu.rw', 'Edna', 'Henry', 8),
(40, 1, 'lydia.brun@zedekak.md', 'Lydia', 'Brun', 7),
(41, 1, 'jay.blake@ral.mk', 'Jay', 'Blake', 10),
(42, 1, 'isabel.serafini@turuhu.bh', 'Isabel', 'Serafini', 10),
(43, 1, 'rebecca.carter@omjo.et', 'Rebecca', 'Carter', 8),
(44, 1, 'maurice.fabbrini@rig.bh', 'Maurice', 'Fabbrini', 9),
(45, 1, 'ollie.turnbull@sicewap.org', 'Ollie', 'Turnbull', 6),
(46, 1, 'jerry.hopkins@fo.mh', 'Jerry', 'Hopkins', 9),
(47, 1, 'nora.lyons@gegijap.na', 'Nora', 'Lyons', 10),
(48, 1, 'anne.weis@kuvesa.pe', 'Anne', 'Weis', 7),
(49, 1, 'louise.gauthier@lapahu.mt', 'Louise', 'Gauthier', 6),
(50, 1, 'lloyd.fani@zev.ru', 'Lloyd', 'Fani', 8),
(51, 1, 'maud.dunn@nabeaga.ni', 'Maud', 'Dunn', 6),
(52, 1, 'henry.gigli@kaot.ps', 'Henry', 'Gigli', 6),
(53, 1, 'virgie.werner@tawuctuj.cf', 'Virgie', 'Werner', 10),
(54, 1, 'gregory.cozzi@eh.ru', 'Gregory', 'Cozzi', 8),
(55, 1, 'lucinda.gil@fajjusuz.kr', 'Lucinda', 'Gil', 7),
(56, 1, 'gertrude.verbeek@pave.cc', 'Gertrude', 'Verbeek', 6),
(57, 1, 'mattie.graham@ispaviw.gt', 'Mattie', 'Graham', 7),
(58, 1, 'bryan.shaw@ha.ee', 'Bryan', 'Shaw', 9),
(59, 1, 'essie.adams@iliat.cw', 'Essie', 'Adams', 8),
(60, 1, 'gary.osborne@do.ga', 'Gary', 'Osborne', 7);